internal class Program
{
    private const string FileLocation = @"";

    private static Dictionary<string, string> appmonDictionary = new() {
        {"アドモン", "Addmon"},
        {"エイドモン", "Aidmon"},
        {"オクショモン", "Auctiomon"},
        {"バッテリモン", "Batterimon (Appmon)"},
        {"ビューティモン", "Beautymon"},
        {"バイオモン", "Biomon"},
        {"ブックモン", "Bookmon"},
        {"ブートモン", "Bootmon"},
        {"ブレモン", "Bramon"},
        {"カリキュモン", "Calcumon"},
        {"カレンダモン", "Calendamon"},
        {"コールモン", "Callmon"},
        {"キャメラモン", "Cameramon"},
        {"カードモン", "Cardmon (Appmon)"},
        {"カリスモン", "Charismon"},
        {"コーチモン", "Coachmon"},
        {"コメットモン", "Cometmon"},
        {"コンパスモン", "Compassmon"},
        {"コンサルモン", "Consulmon"},
        {"クックモン", "Cookmon"},
        {"コーデモン", "Coordemon"},
        {"コピペモン", "Copipemon"},
        {"クラフトモン", "Craftmon"},
        {"ダメダモン", "Damedamon"},
        {"ダンスモン", "Dancemon"},
        {"ダンテモン", "Dantemon"},
        {"デンパモン", "Denpamon"},
        {"デウスモン", "Deusmon"},
        {"デジップモン", "Dezipmon"},
        {"ダイアリモン", "Diarimon"},
        {"ダイスモン", "Dicemon"},
        {"ドクモン", "Docmon"},
        {"ドーガモン", "Dogamon"},
        {"ドガッチモン", "DoGatchmon"},
        {"ドカモン", "Dokamon"},
        {"ドープモン", "Dopemon"},
        {"ドスコモン", "Dosukomon"},
        {"ドローモン", "Drawmon"},
        {"ドリーモン", "Dreammon"},
        {"ドレスモン", "Dressmon"},
        {"エコモン", "Ecomon"},
        {"エフェクモン", "Effecmon"},
        {"エンタモン", "Entermon"},
        {"フェイクモン", "Fakemon"},
        {"フリックモン", "Flickmon"},
        {"ガイアモン", "Gaiamon (Appmon)"},
        {"ガシャモン", "Gashamon"},
        {"ガッチモン", "Gatchmon"},
        {"ゲンゴーモン", "Gengomon"},
        {"グローブモン", "Globemon"},
        {"ゴミモン", "Gomimon"},
        {"ゴシップモン", "Gossipmon"},
        {"ググモン", "Gugumon"},
        {"ハックモン", "Hackmon (Appmon)"},
        {"ハデスモン", "Hadesmon"},
        {"ジャミングモン", "Jammingmon"},
        {"ジェットモン", "Jetmon"},
        {"ジショモン", "Jishomon"},
        {"ジャンププラスモン", "Jumpplusmon"},
        {"カベモン", "Kabemon"},
        {"カイモン", "Kaimon"},
        {"カケイモン", "Kakeimon"},
        {"コソモン", "Kosomon"},
        {"ライブラモン", "Libramon"},
        {"ライトモン", "Lightmon"},
        {"ロガモン", "Logamon"},
        {"ロギモン", "Logimon"},
        {"ラックモン", "Luckmon"},
        {"メールモン", "Mailmon"},
        {"エムシーモン", "Mcmon"},
        {"メディアモン", "Mediamon"},
        {"メディックモン", "Medicmon"},
        {"メッセモン", "Messemon"},
        {"ミエーヌモン", "Mienumon"},
        {"ミニコメットモン", "Mini Cometmon"},
        {"ミラーモン", "Mirrormon"},
        {"マネーモン", "Moneymon"},
        {"マッスルモン", "Musclemon"},
        {"ミュージモン", "Musimon"},
        {"ナビモン", "Navimon (Appmon)"},
        {"ニュースモン", "Newsmon"},
        {"オフモン", "Offmon"},
        {"オンモン", "Onmon"},
        {"オンパモン", "Onpamon"},
        {"オウジャモン", "Oujamon"},
        {"ウラノスモン", "Ouranosmon"},
        {"ペコモン", "Pekomon"},
        {"ペロリモン", "Perorimon"},
        {"ピーポモン", "Pipomon"},
        {"ポコモン", "Pokomon (Appmon)"},
        {"ポセイドモン", "Poseidomon"},
        {"プロテクモン", "Protecmon"},
        {"パズルモン", "Puzzlemon"},
        {"レースモン", "Racemon"},
        {"レイドラモン", "Raidramon"},
        {"リブートモン", "Rebootmon"},
        {"レコモン", "Recomon"},
        {"レッシャモン", "Resshamon"},
        {"レビューモン", "Reviewmon"},
        {"リバイブモン", "Revivemon"},
        {"ロアモン", "Roamon"},
        {"ロケットモン", "Rocketmon"},
        {"ロープレモン", "Ropuremon"},
        {"サクシモン", "Sakusimon"},
        {"サンタモン", "Santamon"},
        {"サテラモン", "Sateramon"},
        {"セーブモン", "Savemon"},
        {"スコープモン", "Scorpmon"},
        {"セットモン", "Setmon"},
        {"ショットモン", "Shotmon"},
        {"シャットモン", "Shutmon"},
        {"スリープモン", "Sleepmon"},
        {"ソーシャモン", "Sociamon"},
        {"スパモン", "Spamon"},
        {"スペシャモン", "Speciamon"},
        {"スカシモン", "Sukasimon"},
        {"スーパーモン", "Supermon"},
        {"サプリモン", "Supplemon"},
        {"スワイプモン", "Swipemon"},
        {"タップモン", "Tapmon"},
        {"タロットモン", "Tarotmon"},
        {"テラーモン", "Tellermon"},
        {"タイムモン", "Timemon"},
        {"トリックモン", "Trickmon"},
        {"トリップモン", "Tripmon"},
        {"ツブモン", "Tubumon"},
        {"チュートモン", "Tutomon"},
        {"ウラテクモン", "Uratekumon"},
        {"ベガスモン", "Vegasmon"},
        {"バイラモン", "Virusmon"},
        {"Ｖジャンプモン", "Vjumpmon"},
        {"ワープモン", "Warpmon"},
        {"ワルダモン", "Warudamon"},
        {"ウォッチモン", "Watchmon"},
        {"ウェザドラモン", "Weatherdramon"},
        {"ウェザーモン", "Weathermon"},
        {"ヤドモン", "Yadomon"}
    };

    private async static Task Main(string[] args)
    {
        var allText = await File.ReadAllTextAsync(FileLocation);

        foreach (var appmonKeyValue in appmonDictionary)
        {
            allText = allText.Replace(appmonKeyValue.Key, appmonKeyValue.Value);
        }

        await File.WriteAllTextAsync(FileLocation, allText);
    }
}